# config.yml
users:
  success:
    username: standard_user
    password: secret_sauce
  failure:
    username: wrong_user
    password: User123

pages:
  saucedemo:
    url: https://www.saucedemo.com/

apis:
  pokemon:
    base_url: https://pokeapi.co/api/v2

environment:
  timeout: 10